In [1]:
#Q1
import numpy as np
import random
import gym

In [6]:
#Q2
#Creating the environment
env = gym.make("Taxi-v3",render_mode="human")
#self._disable_render_order_enforcing : bool = True
env.reset()
env.render()

In [4]:
#Q3
#finding the number of states and actions
print(env.observation_space.n)
print(env.action_space.n)

500
6


In [5]:
#Q4
#Setting values for the learning rate, discount factor and epsilon(a fix value to overcoming the expiration and exploration
#fixing the q values after some duration.)
alpha = 0.1 #learning rate
gamma = 0.6 #discount factor
epsilon = 0.1

In [6]:
#Q5
#Creating the initial Q-table
q_table = np.zeros((500,6))
q_table

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
#Q6
#Training the Q Table
num_of_eposides = 100000

for episode in range (0,num_of_eposides):
    #Reset the environement
    state = env.reset()
    
    #Initialize the variables
    reward = 0
    terminated = False
    
    while not terminated:
        #Take learned path or explore new actions based on the epsilon
        if random.uniform(0,1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])
            
        #Take action
        next_state, reward, terminated, info = env.step(action)
        
        #Real accurate
        q_value = q_table[state,action]
        max_value = np.max(q_table[next_state])
        new_q_value = (1 - alpha) * q_value + alpha * (reward + gamma * max_value)
        
        #Update Q-table
        q_tables[state,action] = new_q_value
        state = next_state

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [7]:
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#Q8
#Testing the goodness of the trained table
total_penalties = 0
num_of_episodes = 100

for _ in range(num_of_episodes):
    state = env.reset()
    penalties = 0
    reward = 0
    terminated = False
    
    while not terminated:
        action = np.argmax(q_table[state])
        state,reward,terminated,info = env.step(action)
        
    if reward <= 10:
        penalties += 1
total_penalties += penalties 

In [ ]:
print(total_penalties / num_of_episodes)