In [10]:
import tensorflow as tf #importing tensorflow
print(tf.version) #prints the tensorflow version

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Binura\\anaconda3\\envs\\tfradeon\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [11]:
#creating tensors
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567,tf.float64)
print(floating)
print(string)
print(number)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>


In [12]:
#creating tensors of higher degrees/ranks
rank1_tensor = tf.Variable(["Test"],tf.string)
rank2_tensor = tf.Variable([["1,2],[3,4],[5,6"]],tf.int16)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=string, numpy=array([[b'1,2],[3,4],[5,6']], dtype=object)>


In [13]:
#determining the rank of a tensor
tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
#shape of the tensor
rank2_tensor.shape

TensorShape([1, 1])

In [18]:
#changing the shape of a tensor
tensor1 = tf.ones([1,2,3]) #this creates a shape [1,2,3] tensor full of ones.
tensor2 = tf.reshape(tensor1,[2,3,1]) #reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2,[3,-1]) #-1 tells the tensor to calculate the size of the dimension in that place and this will reshape the tensor to [3,3].
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [19]:
#creating a 2D vector
matrix = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
tensor = tf.Variable(matrix,dtype = tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [20]:
three = tensor[0,2] #selects the 3rd element from the first row
print(three)

row1 = tensor[0] #selects the first row
print(row1)

column1 = tensor[:,0] #selects the first column
print(column1)

column_1_in_row_2_and_3 = tensor[1:3,0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
