In [ ]:
#Creating variables and assigning numbers, strings, floating values to them
name = "Oshada"
no_studs = 150
temp = 13.0
print(name)
print(no_studs)
print(temp)

In [17]:
#Creating a list
List_1 = [1,2,3,4,5,6,7,8,9,10]
List_2 = list(range(0,20))
List_3 = [x for x in range(10)]

print(List_1)
print(List_2)
print(List_3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [24]:
#printing odd numbers using a for loop
print("Odd numbers of list1")
for e in List_1:
    if e%2 != 0:
        print(e,end=' ')
print()

print("Odd numbers of list2")        
for e in List_2:
    if e%2 != 0:
        print(e,end=' ')
print()

print("Odd numbers of list3")
for e in List_3:
    if e%2 != 0:
        print(e,end=' ')

Odd numbers of list1
1 3 5 7 9 
Odd numbers of list2
1 3 5 7 9 11 13 15 17 19 
Odd numbers of list3
1 3 5 7 9 

In [23]:
#printing odd numbers using a while loop
i = 0
print("Odd numbers of list1")
while i < len(List_1):
    if List_1[i] %2 != 0:
        print(List_1[i],end=' ')
    i+=1
print()

j=0
print("Odd numbers of list2")
while j < len(List_2):
    if List_2[j] %2 != 0:
        print(List_2[j],end=' ')
    j+=1
print()

k=0
print("Odd numbers of list3")
while k < len(List_3):
    if List_3[k] %2 != 0:
        print(List_3[k],end=' ')
    k+=1

Odd numbers of list1
1 3 5 7 9 
Odd numbers of list2
1 3 5 7 9 11 13 15 17 19 
Odd numbers of list3
1 3 5 7 9 

In [25]:
#printing odd numbers using list comprehension
List_2 = [x for x in List_1 if x%2 != 0]
print(List_2)

[1, 3, 5, 7, 9]


In [26]:
#generate a list which contains all numbers from 0 to n which are odd and have been squared using list comprehensions.
List_3 = [x for x in[x**2 for x in range(7)]if x%2 != 0]
print(List_3)

[1, 9, 25]


In [33]:
#creating a function
def get_odd(n):
 return[x for x in[x**2 for x in range(n)]if x%2 != 0]

In [36]:
#replacing the word cookies with the word apples
lista = ['I','like','cookies']
listb = lista
listb = [s.replace('cookies','apples') for s in listb]
print(lista)
print(listb)

['I', 'like', 'cookies']
['I', 'like', 'apples']


In [39]:
#creating a dictionary
d1 = {x:x**2 for x in range(7)}
print(d1)

vals = list(d1.values())
vals

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36}


[0, 1, 4, 9, 16, 25, 36]

In [40]:
#reversing a string
a=[0,1,2,3,4,5][::-1]
print(a)

[5, 4, 3, 2, 1, 0]


In [46]:
#zipping of lists
xcoors = [0,1,2,3,4,5]
ycoors = [6,7,8,9,10,11]
zcoors = [99,98,97,96,95,94]
xycoors = [(0,6),(1,7),(2,8),(3,9),(4,10),(5,11)]
zip_list = list(zip(xcoors,ycoors,zcoors))
chocage = [(20,8),(33,8),(27,14),(66,23),(90,100)]
unzip_list = list(zip(*chocage))

print(zip_list)
print(unzip_list)

[(0, 6, 99), (1, 7, 98), (2, 8, 97), (3, 9, 96), (4, 10, 95), (5, 11, 94)]
[(20, 33, 27, 66, 90), (8, 8, 14, 23, 100)]


In [50]:
#creating a numpy array of floats containing the numbers from 0-4
import numpy as np
arr0 = np.array([1,2,3,4],float)
print(arr0)

[1 2 3 4]


In [51]:
#creating a matrix
arr1 = np.array([[1,2,3],[4,5,6]],float)
print(arr1)

[[1. 2. 3.]
 [4. 5. 6.]]


In [52]:
#getting the shape of the matrix M
arr1.shape

(2, 3)

In [53]:
#check if the value 2 is in the matrix M
print(2 in arr1)

True
